
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS GUESTS;
DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS PAYMENT;

CREATE SEQUENCE IF NOT EXISTS ROOM_SEQ;
CREATE SEQUENCE IF NOT EXISTS GUESTS_SEQ;
CREATE SEQUENCE IF NOT EXISTS BOOKING_SEQ;
CREATE SEQUENCE IF NOT EXISTS PAYMENT_SEQ;


CREATE TABLE ROOM(
  ROOM_ID BIGINT DEFAULT ROOM_SEQ.nextval,
  NAME VARCHAR(16) NOT NULL,
  ROOM_NUMBER CHAR(2) NOT NULL UNIQUE,
  BED_INFO CHAR(2) NOT NULL,
  PRIMARY KEY (ROOM_ID)
);

CREATE TABLE GUEST(
  ID BIGINT DEFAULT GUESTS_SEQ.nextval,
  GUEST_ID BIGINT NOT NULL,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(64),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24),
  PRIMARY KEY (GUEST_ID)
);

CREATE TABLE BOOKING(
  ID BIGINT DEFAULT BOOKING_SEQ.nextval,
  BOOKING_ID BIGINT NOT NULL,
  ROOM_ID BIGINT NOT NULL,
  GUEST_ID BIGINT NOT NULL,
  ARRIVAL_DATE DATE NOT NULL,
  DEPARTURE_DATE DATE NOT NULL,
  RESERVATION_STATUS VARCHAR(16) NOT NULL,
  PRIMARY KEY (BOOKING_ID),
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM,
  FOREIGN KEY (GUEST_ID) REFERENCES GUEST

);

CREATE TABLE PAYMENT(
  ID BIGINT DEFAULT PAYMENT_SEQ.nextval,
  BOOKING_ID BIGINT NOT NULL,
  FOREIGN KEY (BOOKING_ID) REFERENCES ROOM
);

CREATE INDEX IDX_RES_DATE ON BOOKING (ARRIVAL_DATE);